### ISSUE TITLE
[BUG] No Github PR permission for `Crowdin Contributors Action`

### ISSUE THREAD

**Issue by RealRichi3** [the-turing-way/the-turing-way#3419]
### Description

The Github action for Crowdin Contributors needs to raise a pull request to update the README file. But from the error i found, i think it doesn't have permission to raise pull requests

Ref #3183 #3184

#### Expected behaviour

The workflow is expected to pull data from Crowdin, Write the data to the README file and raise a pull request to update it.

#### Actual behaviour

It successfully fetches the data and writes to the README file, but an error occurs when it attempts to raise a PR to update the main branch.

### How to reproduce

1. Go to 'actions' tab
2. Click on 'Crowdin Contributors Action'
3. Run workflow manually

### Failure Logs
This is the error i found from the action logs
![Screenshot from 2023-11-15 23-09-43](https://github.com/the-turing-way/the-turing-way/assets/76791916/7845ec1e-0d39-4709-a7c4-25c8f339f546)

**Comment by sgibson91** [comment]
We may need to set the following in the workflow file

```
permissions:
  pull-requests: write
```

See docs here: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

**Comment by RealRichi3** [comment]
Alright, thanks. I'll raise a PR now

**Comment by sgibson91** [comment]
I just reran it and it failed for me too. But note this error message:

> remote: Permission to the-turing-way/the-turing-way.git denied to github-actions[bot].

The issue is not regarding what permissions you or I (or anyone else) has on the repo, but the permissions that the `GITHUB_TOKEN` has on the repo. I'll look into this more during the week.

**Comment by RealRichi3** [comment]
alright, thanks @sgibson91

**Comment by sgibson91** [comment]
I opened https://github.com/the-turing-way/the-turing-way/pull/3437 and triggered it manually, thinking the action needed write permissions to content as well as pull requests, but the action still failed with this error message:

>  Error: GitHub Actions is not permitted to create or approve pull requests.

I thought this was really weird, so went clicking around the settings in the repo and found in the Actions tab, there is a checkbox to permit GitHub Actions to create (and approve) pull requests. The fact that this is greyed out for me is worrying because I am an Admin on the repo and an Owner on the organisation and hence have the maximum amount of permissions... I may have to email GitHub Support.

<img width="879" alt="Screenshot 2023-11-20 at 15 44 30" src="https://github.com/the-turing-way/the-turing-way/assets/44771837/a1e7aff2-b4ce-4056-b2a9-e7d0fd7d811c">

**Comment by RealRichi3** [comment]
> I opened #3437 and triggered it manually, thinking the action needed write permissions to content as well as pull requests, but the action still failed with this error message:
> 
> > Error: GitHub Actions is not permitted to create or approve pull requests.
> 
> I thought this was really weird, so went clicking around the settings in the repo and found in the Actions tab, there is a checkbox to permit GitHub Actions to create (and approve) pull requests. The fact that this is greyed out for me is worrying because I am an Admin on the repo and an Owner on the organisation and hence have the maximum amount of permissions... I may have to email GitHub Support.
> 
> <img alt="Screenshot 2023-11-20 at 15 44 30" width="879" src="https://user-images.githubusercontent.com/44771837/284319031-a1e7aff2-b4ce-4056-b2a9-e7d0fd7d811c.png">

I think we'll have to email github support, or are there  higher roles than Admin

**Comment by JimMadge** [comment]
This is at org level:

<img width="670" alt="Screenshot 2023-11-20 at 16 02 58" src="https://github.com/the-turing-way/the-turing-way/assets/23616154/cae3c1c4-4c85-4805-99eb-40a6e73aa872">

> Repository administrators will only be able to change the default permissions to a more restrictive setting.

**Comment by sgibson91** [comment]
Ok, good to know that I'm not losing my marbles, thanks!

I personally think that GitHub Actions opening PRs is a very normal workflow (as evidenced by this bug report!) so would vote for turning this on (I need convincing on the approval bit but we don't have that granularity so we'll park that discussion)

**Comment by sgibson91** [comment]
> there higher roles than Admin

There are no higher roles than admin on a repo, or Owner on an org. I literally have all the power 😆 Thankfully, Jim saved us by noting this is an org-wide setting.

**Comment by sgibson91** [comment]
I turned this on in the org settings, and then re-ran the action with my changes in this PR https://github.com/the-turing-way/the-turing-way/pull/3437

The permissions of our `GITHUB_TOKEN` are set to be read-only unless otherwise set by the `permissions` key, so I do believe this PR is needed.

And running it successfully opened a Crowdin PR! https://github.com/the-turing-way/the-turing-way/pull/3439 (to the wrong branch though 😅 )

**Comment by sgibson91** [comment]
TADA!! 🎉 https://github.com/the-turing-way/the-turing-way/pull/3440
