### ISSUE TITLE
How should we name The Turing Way Community calls

### ISSUE THREAD

**Issue by AlexandraAAJ** [the-turing-way/the-turing-way#3579]
Dear all, we need your help!

Ties to the issue about [2024 Turing Way Community Calls Dates and Planning Steps](https://github.com/the-turing-way/the-turing-way/issues/3528).

**On February 15th, The Turing Way held its inaugural [2024 Community Call](https://annuel2.framapad.org/p/TTW-community-call-15Feb). Feedback indicated that some participants found the name of the call unclear in terms of its purpose. We're seeking a new name that effectively communicates the aim of the call, making it easier to promote and understand. Below are the details of the calls for your reference**:

In 2024, we are commencing a series of open [INSERT NAME HERE] that bring together any member of The Turing Way community - including people who have not yet contributed to the project! Modelled off a political town hall event these online sessions are an opportunity to better understand activities across the project and how decisions are made. Our aim is to leverage the expertise across our community and we explicitly invite you to review our processes and recommend improvements. We expect that the calls will be a mix of celebration, feedback, and opportunities to build connections with other organisations and initiatives around the world. Currently, this call is hosted in English. This call will be recorded for use by participants, and will use Zoom's automatic captioning. This call may also involve live discussion, screen-sharing, and other interactive activities that may be internet bandwidth-intensive. Slides will be shared after the call. A shared document will be used for collaborative note-taking, capturing feedback and learning.

Please vote with an emoji which of the names you consider better?:
🎉  _The Turing Way_ Forum
🚀  _The Turing Way_ Town Hall
❤️  _The Turing Way_ Community Call
* Other name, please comment

### What needs to be done?
Please help us to choose which name is the best one 

### Who can help?
Everyone

**Comment by AlexandraAAJ** [comment]
@aleesteele, could you please include this on the weekly announcements on Monday?

**Comment by KirstieJane** [comment]
@AlexandraAAJ - can you adjust the emojis to being ones that work on GitHub?

Maybe:

🎉 The Turing Way Forum
🚀 The Turing Way Town Hall
❤️ The Turing Way Community Call

**Comment by aleesteele** [comment]
Posted in the community channel on slack for wider exposure – and will use this information for our March 2024 newsletter: https://github.com/the-turing-way/newsletter/issues/12

**Comment by ragamouf** [comment]
I voted for Forum over Town Hall because it conveys a stronger vibe of a place to highlight contributions from the many to share with each other. In my experience, a "Town Hall meeting" means management or the council are sharing their plans for why they are building a freeway through the local forest, and undertaking the lip service to say they are doing consultation. I don't have experience with "political Town Hall" events.

Both "Town Hall" and "Forum" sound more strategic than "Community Call" when I'm reporting back to my organisation about external engagement. 

I note also there are more rockets (6) at this moment over on the slack, so I'm interested in other reasons why Town Hall is a good idea. I am open to having my mind changed on this!

**Comment by JimMadge** [comment]
Agreed that "Forum" sounds more official/serious than "Community Call". I would think that "Community Call" sounds welcoming but perhaps it also sounds more like a casual chat rather than a place to get involved or have impact on the project?

I think it is also worth thinking/asking whether the registration process caused any problems. It was a new system to me and I got a little confused trying to join the call.

Adding a registration is a (small) barrier to joining but I suppose it is a balance between that and other benefits (knowing how many people will join, some protection against people crashing the calls, and so on).

**Comment by EstherPlomp** [comment]
I'm happy with both 'Forum' and 'Town Hall' - I like the concept of Town Halls because it feels more tied to a physical place I suppose. This is more of a personal preference than anything else :)

**Comment by KirstieJane** [comment]
A message from @malvikasharan and me from the Turing Way project management meeting - lets go with Turing Way Forum!

Thank you everyone for the great input and votes 🙏
