### ISSUE TITLE
[NEW CHAPTER] - Alternative models of culture change

### ISSUE THREAD

**Issue by Arielle-Bennett** [the-turing-way/the-turing-way#3640]
### Title

Models of culture change

### Guide

Ethical Research

### Summary of proposed chapter

Following discussions in the Turing Way Slack, we're proposing to move the "culture change" subchapter in the Activism chapter of the Ethical Research Guide into it's own chapter, and to revise / expand it with a critical look at culture change models commonly encountered in open practices/research such as https://www.cos.io/blog/strategy-for-culture-change

We think this might form part of the June 2024 Book Dash

### Resources

- https://www.cos.io/blog/strategy-for-culture-change
- https://doi.org/10.1146/annurev-psych-020821-114157
- https://doi.org/10.31219/osf.io/x2w9h
- https://the-turing-way.netlify.app/ethical-research/activism/activism-cultural-change.html
- notes from the social discussion during Book Dash: https://annuel2.framapad.org/p/ttw-bookdash-june24-day4
- [A Practical Guide to Systemic Change](https://www.youtube.com/watch?v=3NCSY85FqVQ&t=2991s) shared by @BatoolMM 
- https://elifesciences.org/collections/edf1261b/research-culture-a-selection-of-articles

### Who can help?

- Anyone interested in critical examination of different models of culture change in open practices 

### Updates

- [ ] Write chapter outline
- [ ] Add material to the chapter
- [ ] Combine materials into a readable chapter
- [ ] Proofread
- [ ] Create PR and link in the comments
- [ ] Request reviews
- [ ] Address reviews
- [ ] Merge to main branch

**Comment by Arielle-Bennett** [comment]
Just want to note that we're discussing this at a social session during the Book Dash on Thurs - then we'll start writing up a draft :)

**Comment by Arielle-Bennett** [comment]
Hello! Today's social session was really fun, the collaborative whiteboard is below and the notes will be transferred to a shared doc that can be used for drafting. It was a really great discussion so thanks everyone for participating! 

[Culture Change Discussion - The Turing Way Book Dash_frames-[1717685497959].pdf](https://github.com/user-attachments/files/15678839/Culture.Change.Discussion.-.The.Turing.Way.Book.Dash_frames-.1717685497959.pdf)

**Comment by EstherPlomp** [comment]
Notes from the Culture Change Discussion pdf: 

What are the different factors we need to consider when thinking about research culture change?
- What are the attitudes of different hierarchical levels towards change
- How technically feasible is it to enact changes in practice
- 1-I am trying to differentiate between cultures change & system change
- 2-Culture change requires an alignment between systems and behaviour, and I see what “open science” needs (at this stage) is systematic change. But we have to always
- 3-System are feedback loops, attempts to shift culture without addressing the system won’t work.
- 4-In order to change the system, we need strategy & operations, leadership
- Transition to change, taking care of the community. Offer spaces to discuss the changes
- How it will affect different people; do the changes consider everyone/affect some people (positively/negatively) more
- Agree on change timelines and be very explicit with how the changes will impact different actors
- Change takes time
- People don't like change (the academic system itself even less)
- People are more easily swayed if key players change first
- Preexisting biases and notions
- Provide training about change management
- what outcomes are you hoping will emerge from change, what are the benefits and who benefits?
- How do we get people excited about change? TLDR: most often people oppose change
- It needs to address a concern/issue that people face
- What does success look like? Could you measure it?
- How do we have HOPE when facing all the current problems in research??
- The approach and the structure of the system - a hierarchical system vs a flat one vs a bottom up will requires different approaches
- What are the current incentives in the culture?
- Use thoughtful and sensitive language when discussing culture change. Say what you mean, and mean what you say.
