### ISSUE TITLE
Book Dash Working Group: Is The Turing Way Open Source ?

### ISSUE THREAD

**Issue by AbcSxyZ** [the-turing-way/the-turing-way#3653]
# Is The Turing Way Open Source ?

> *« The Turing Way project is open source, open collaboration, and community-driven. »*  
> [The Turing Way homepage](https://the-turing-way.netlify.app/index.html)

What is « open source » ? The common answer, as we can see in the handbook, is about a software with an available source code that can be used, modified and shared, some will speak of the [Open Source Definition](https://opensource.org/osd). Then, is The Turing Way a software, is The Turing Way not open source, or could open source not be about software?

This is a proposal for the book dash from 3 to 7 June to set up a working group to bring open source confusion to the community in order to clarify this fundamental concept. A week for some sort of open research to try to determine whether The Turing Way is « open source » or not in an attempt to contribute to the very definition of « open source ».

If The Turing Way is open source, what is open source? A way to contribute to make this manual explain its own nature.

## The Open Source Confusion

What is open source ? A tough question, isn't it ?

There may not yet be a good answer to this question. There is debate, and it doesn't seem that there is to date a single definition that captures the whole concept.

Adopted following the essay the [Cathedral and the Bazaar](https://en.wikipedia.org/wiki/The_Cathedral_and_the_Bazaar) by Eric Raymond, [formalized in 1998](https://opensource.com/article/18/2/coining-term-open-source-software) in response to confusion factors surrounding « free software », open source has at least these 2 major confusion factors:

### 1/ Open Source Beyond Software

Is the following image an open source image? How to benefit from this modification right?

![open-source-image](https://github.com/the-turing-way/the-turing-way/assets/34010605/7ac9df4b-fdfc-4fff-b25b-eaa6c7a208b0)

> *If you provide the source for the image so that I can modify it and it uses an OSI compliant license, then yes, I would say it's an open source image.*
>
> *What constitutes Open Source or not is very clear now for software, but for other artifacts, that might not be so clear.*  
> **A member of the Open Source Initiative in a private email.**

In its glossary on the notion of [open source](https://docs.github.com/en/get-started/learning-about-github/github-glossary#open-source), GitHub mentions that the concept extend beyond software. It is the result of a discussion around 2014 and a reflection by a GitHub employee which can be seen in his article: « [Open source, not just software anymore](https://ben.balter.com/2014/01/27/open-collaboration/) ». Using the example of blogs and their text files.

It seems that the notion of source makes sense for different types of digital resources, the source(s) used to create a resource. Some people then describe their availability as "open source".

Like for a pdf with its LaTeX file, like on arXiv [articles](https://arxiv.org/abs/2107.14330) where you have a link to download « TeX Source ». In the field of open education, a paper was published to suggest the notion of « open source educational resource » [[doi:10.48550/arXiv.2107.14330](https://doi.org/10.48550/arXiv.2107.14330)] to distinguish OER with available sources. An Open-o-Meter [[doi:10.1016/j.procir.2018.08.306](https://doi.org/10.1016/j.procir.2018.08.306)] was developed for open hardware build around the question of the various sources which compose a design. The issues surrounding sources can be found around other resources such as for music and video.

In setting up its process for defining « [open source AI](https://opensource.org/deepdive) », the Open Source Initiative is showing that their current definition has limitations, with AI possibly being simply another type of artefact other than software made from [multiple components](https://opensource.org/deepdive/drafts/the-open-source-ai-definition-draft-v-0-0-8) (model, source code, data).

Access to sources is therefore a key component in the ability to modify a resource. Does open source is more about sharing software with their source code or sharing digital resources with their sources?

Beyond open source software, is there open source resources ?

### 2/ Open Source and restrictions: a binary notion or a continuum ?

What is open source and what is not?

Frequently, open source is defined according to the Open Source Definition of the Open Source Initiative, which specifies that to be considered as open source a software must use a licence that does not discriminate against any use or any person. Your software licence complies with the Open Source Definition, your software is open source.

But there is debate, already introduced in the [Turing Way](https://the-turing-way.netlify.app/reproducible-research/licensing#what-are-usage-restricting-licenses).

> *Ultimately, we are the heart and soul of FLOSS, not the Free Software Foundation or the Open Source Initiative or GitHub. We have the responsibility to put ethical principles over the philosophical purity of 'software freedom'.*  
> [Co-founder of the Organization for Ethical Source](https://leaddev.com/continuous-learning/open-source-ethical-source)

The Open Source Definition is the source of political dissensus on the meaning of open source. Semantic conflicts that lead to social conflicts. Openness is a double-edged sword, a variety of more or less open licences exist for sharing resources, and some will introduce clauses for ethical, commercial or other reasons.

> *There are two approaches to open source: orthodox and commercial. As a VC, we stick to the latter and consider e.g. Elastic and MongoDB as COSS companies, despite SSPL is not approved by the OSI. The same for @OpenReplayHQ and many others.*  
> [General Partner of a VC fund](https://danb.me/blog/redefining-open-source-runa/)

Some people disqualify some types of resources as open source based on the OSD, suggesting that it should be called something else (source available, ethical source, etc.), while some others find themselves having existential questions about the terms they are allowed to use, and finally choosing to adopt the notion of open source despite social pressures.

The notion of open source is subject to interpretation and dissent. With diverging opinions, what then could open source truly be?

With the notion of open source potentially extending to resources, this is a question that can arises in view, for example, of the widespread use of CC NC licences coming from a broad non-commercial culture in the (open) education sector.

Where is the boundary between open and closed, between what is open source and what is not?

## Proposed Objective for the Working Group

**The idea would be to try to figure out what the community think of the following question: is The Turing Way open source?**

If so, seeking to support this statement within the handbook content through a more consistent explanation of open source, and let the handbook explain itself. If not, avoid qualifying the Turing Way as open source to prevent confusion.

The interest will be to bring these various questions about the confusion surrounding open source to foster their consideration, and figure out what are the implications.

## Benefits

Being able to say whether The Turing Way is open source or not, and why! The usefulness will be to provide a more robust definition and explanation of open source within the handbook, which can then more broadly help people who need to explain the concept.

The meaning we give to open source determines the way we interact with digital resources. Is at play a whole way of sharing digital resources, influencing the way in which these practices of openness are carried out and affecting the availability of resources' sources.

A more robust understanding of open source can empower people on how they use, modify and share open resources.

## A Contribution to the Definition of Open Source

The meaning of open source is a current debate. As open source is about software, determining if The Turing way is open source is a critical question for the very definition of open source. This is a proposal related to the project [open-source-undefined.org](https://open-source-undefined.org/) with the aim to foster the debate over the meaning of open source. Answering this question for the Turing Way may help to provide some evidence about what open source may be.

The meaning that the Turing way gives to open source can shed light on the meaning of the concept.

If you're interested in working on open source from 3 to 7 June during the book dash, I can invite you to introduce yourself in the comments and tell us about what might interest you about taking part in this initiative, share your understanding of the notion or even your experience with open source confusion!

Is the Turing Way open source ? Why or why not ?

![turing way book dash](https://github.com/the-turing-way/the-turing-way/assets/34010605/5e5c68ef-84c9-4b25-b67c-78fe6b556ee7)

**Comment by malvikasharan** [comment]
Hi Simon, this sounds like a great proposal for a social discussion during the Book Dash, rather than a working group. I love the analysis you have provided and I am inclined to saying that you have made a good case for us to improve the definition of open source in the open research chapter.

Turing Way uses open source framework for collaborative, peer production and maintenance of the project. We use Open source software as underlying infrastructure, all contents are openly sourced and highly relies on open source communities for its sustainability, I am happy to join in the discussions to unpack why I think and hence we have stated Turing Way as an open source project. Thank you for raising this in Slack, I will ping the Book Dash committee there on Monday to ask if we can have this added in the social discussion during the week.

**Comment by AbcSxyZ** [comment]
It would be very interesting to see your vision of open source, so not as the person who initiated the project but as the one who introduced this qualifier (commit [6f9af4b](https://github.com/the-turing-way/the-turing-way/commit/6f9af4b890ec1a64e95f0116903a019c4f92fa63)), hence this "I". It may be just a discussion, but without any doubt there's plenty of work to fill a week, my current intent being to focus on open source confusion for the entire book dash. With your willingness « to unpack [y]our perspective in the open » and the lack of « formally organised channel/interesting group/working group [...] for these kinds of discussions », there's certainly a lot to imagine. 

Regarding your comment, it seems appropriate to do it now. I mentioned two confusion factors around the meaning of open source, to avoid a lengthy text I omitted another one that I knew would come up sooner or later: the collaboration.

## Is open source about collaboration ?

> *One of the meeting's important results was a general agreement that, in all the variant definitions, public access to source was the most important and only absolutely critical common element.*  
> [Eric Raymond following the Open Source Summit in 1998](https://www.linuxjournal.com/article/2918)

The notion of open source is subject to interpretation between a literal meaning and extra dimensions that can surround the concept.

With a literal interpretation, open source can be only about making a source [code] "open". The term "open" itself being polysemous, with an open to participation which is more closely linked to governance to an open in the sense of making information freely available, the latter being the most basic interpretation.

Following OSI interpretation, a project/software is qualified as open source depending on the license, the collaborative dimension won't be considered. Some open source projects can be then in a truly non-collaborative spirit, like for transparency reasons or to dictate a standard.

Collaboration is not a core value of open source in the sense that it is not an essential, required dimension. The Open Source Definition do not even mention collaboration.

Coming back to the definition of open source by GitHub, it was done in echo of an article « [What Is The Spirit of Open Source?](https://haacked.com/archive/2012/02/22/spirit-of-open-source.aspx/) » where the author had discussions on whether a source code openly available developed behind closed doors and without (external) collaboration could be qualified as open source.

![202713032-c8ec5f1d-5d0d-4115-a60a-0990b4b169f0](https://github.com/the-turing-way/the-turing-way/assets/34010605/efdc37e4-9255-480f-b4fb-77ce64019a11)
Source: [Twitter](https://x.com/tobie/status/1352051091081490432)

The concept of open source is born out of the realisation of the collaborative potential that can take shape around (free) software. The Cathedral and the Bazaar by Eric Raymond, which will lead to « open source », was in 1997 the theorization of a distributed development methodology for (free) software coming from an analysis of the Linux project/community. An influential book that inspired Netscape to open up its browser code, giving birth to Mozilla.

With the interest of these software practices by the business world and the willingness to reach them, with free software confusion factors on top of that, it leads in 1998 to the "coining" of open source by [Christine Peterson](https://opensource.com/article/18/2/coining-term-open-source-software) (but see [pre-1998 usage](https://www.arp242.net/open-source.html)) followed by a kind of "[marketing campaign](http://catb.org/~esr/faqs/hacker-revenge.html)" to spread the world about this particular type of software. A marketing campaign that became the Open Source Initiative.

The notion of open source was not born out of a desire to share code, already a common practice like with free software in 80's, just like collaboration didn't start in 1997 whose benefits could already be felt.

> *In the early '90's, somebody found a way to do a scientific measurement of reliability of software. [...] So they measured it, and the most reliable set of programs was the GNU programs.*  
> [Richard Stallman in the speech « Free Software: Freedom and Cooperation »](https://www.gnu.org/philosophy/rms-nyu-2001-transcript.html)

Open source is born out of collaboration, but collaboration is not a criterion that defines open source. How does collaboration fit in with this concept of open source? Is open source more than making source(s) available ?

## The Turing Way relation to sources

> All contents are openly sourced

So let's check it out!

![The Gnirut Way](https://github.com/the-turing-way/the-turing-way/assets/34010605/d307eb14-30c1-49ae-b92b-34da208bc7a9)

No need to go any further than the [homepage](book.the-turing-way.org) to see that this is not true when it comes to illustrations. As you can see, the figure 1 is editable, I'm able to reuse it in a rather accessible way in case I want to launch a fork called the Gnirut way. The 2nd figure, with my truly limited design skills, can't be edited in the same way.

The first image provides a svg file next to a png file, the second provides only a png/jpg version, sources of images are lacking. According to metadata, it seems that Scriberia illustrations are done with Adobe Photoshop which probably use files with `psd` extension, svg may not even be the primary and most practical source and format for editing this type of illustration.

These illustrations are [shared](https://zenodo.org/records/10654984) with the intent to be reused, without necessarily providing the ability to do so because of the lack of appropriate sources. This is the potential case of « open source images » shown initially.

But this issue with images sources is not limited to these nice illustrations.

![reproducible-matrix](https://github.com/the-turing-way/the-turing-way/assets/34010605/6c02df79-8150-45bd-a5e8-0734b0105164)


This matrix can be found in the [definitions of reproducibility](https://book.the-turing-way.org/reproducible-research/overview/overview-definitions). How can we update this type of resource?

In the absence of sources, a modification will not be trivial, I don't know how I could edit it simply in case I want to define slightly differently reproducible research for The Gnirut Way or if I find a diagram with improvable information.

After images, we can also consider another element: presentations. We can have a look at the [Zenodo community](https://zenodo.org/communities/the-turing-way/) of TTW where this kind of resource seems to be gathered. The way presentations are shared vary between authors, all of them provide a pdf but only a part provide pptx, presentation sources. 227 pdf for 107 pptx, half of the presentations may not have sources which could limit reusability.

The absence of presentation sources has already caused friction, such as around the video « [Scientific Publishing: a brief history and where do we go from here?](https://book.the-turing-way.org/reproducible-research/open/open-access.html) » where someone asked specifically for sources as they were not provided. Sources shared separately on a google drive from a nested comment which, to be FAIR, doesn't seem to be the most appropriate.

All contents are not provided with their sources, it's done inconsistently.

## Related resources on open source from The Turing Way community

Some useful resources to understand how open source is considered at TTW:
- Commit [6f9af4b890ec1a64e95f0116903a019c4f92fa63](https://github.com/the-turing-way/the-turing-way/commit/6f9af4b890ec1a64e95f0116903a019c4f92fa63) by @malvikasharan which introduce open source qualifier.
- [What are the outcomes of openness in AI?](https://jending.medium.com/what-are-the-outcomes-of-openness-in-ai-c57ccdbce896) by @dingaaling
- [Fireside Chat | Adopting open source in Data Science & AI across sectors](https://www.youtube.com/watch?v=NdmkaRmY6jI), showing the implicit on open source around software while qualifying TTW as open source.
- [Fireside Chat | Who is building open source AI? ](https://www.youtube.com/watch?v=e8EBI1ocxt4) in relation to OSI's definition of open source AI
- [Open source software](https://book.the-turing-way.org/reproducible-research/open/open-source) and [licensing](https://book.the-turing-way.org/reproducible-research/licensing) sections of the handbook

**Comment by malvikasharan** [comment]
Thanks, Simon. I don't really have the bandwidth to have the discussion about the Open Source-ness of the book at the moment - but very happy to come back to this in Book Dash week.

Wanted to touch on the other two analyses/observations - so that we can clarify somewhere to be open about the limitations we have:

## Images

Thank you for taking the time to highlight the challenges around editable sources for images -- we, unfortunately, don't have access to those as the images are live sketched and not done in layers that can be easily edited. Producing these images is considered by community members an important part of the Book Dash week. Having an illustrator join us for a day is already very expensive and then paying for the time required to finish the live images is an extra cost. Creating a layered image is not currently offered to us as a service and if we need it there will be more cost attached to that. Therefore, we have settled on having community-contributed co-creation of images that they can reuse. |

## Slides

The point on pptx is a good one - most of the talks reuse existing resources, which are all shared on a shared drive: https://drive.google.com/drive/u/1/folders/1k69Va3ZvtIRiViIpulRc4xlb46bXVf4Y. This is linked here, but maybe we should provide the links to editable versions in the Zenodo entries even when it is not directly uploaded. Although it would be great if you could review and update this chapter recommending that all speakers update pptx versions (including me!): https://the-turing-way.netlify.app/community-handbook/presenting

Do keep sharing about what you are observing as well as where/how we can as a team/community improve.

I am also keen to hear from the @the-turing-way/infrastructure-working-group - particularly from @da5nsy who I have previously discussed this when we made the latest changes in the welcome page.

**Comment by RichardJActon** [comment]
Hi @AbcSxyZ for some context at the last but one book dash I contributed some updates to the chapter on licensing https://github.com/the-turing-way/the-turing-way/pull/3142 and hosted a social session on licensing, IP and digital ownership https://hackmd.io/Q0gEz9x6Rqm6fAiscfNF4Q reflecting on the nature of digital ownership.

Some of my thoughts on the open source definition question: I would suggest the OSI, FSF, and Debian definitions of free/libre or open source software (FLOSS) all largely converge on a definition that pretty much amounts to abiding by the FSF's four freedoms. I also suggest that the common core of these definitions is the one generally being alluded to by people who are at least somewhat informed about this issue. The term is already somewhat overloaded, including as it does permissive and copy left code, so I would strongly favour using other terms to refer to adjacent concepts which diverge from this definition to avoid further terminological confusion.

In my experience people tend to think of open source as permissively licensed, this makes some degree of sense as copy left is in some sense a restriction not obvious from the four freedoms. This constraint is intended to reduce free loading leading to a tragedy of the commons. It tries to do so by imposing the requirement that if you share software built with copy left code you must also share your sources. This, to some degree, encourages making contributions up-stream so that you can benefit from the work done by others maintaining the rest of the code base. It runs into trouble because not everyone is a software engineer who can contribute to every project they use and thus have the game theory of this arrangement work out in their favour so you still get 'free-loaders' (in the purely game theoretic sense for framing this incentives alignment problem - not pejoratively to users of open source projects who don't contribute to them).

The community and collaborative aspects are in my view a second layer made possible by adherence, potentially to somewhat varying degrees, to the 4 freedoms. I would content that the freedoms are necessary but not sufficient for equitable software communities. Just as it should always be possible for people to think and speak their mind it should be possible for people to use free software for any purpose but there should not always be an expectation that exercising these freedoms to the detriment of others will necessarily come without negative consequences.

I think that many things analogise pretty well to software when generalising open source. In the case that you raise of an image distributing just the bitmap is somewhat analogous to distributing just the built binary. However bitmaps are easier to edit than most software binaries and still get a usable result. One might draw analogies to languages which don't ship pre-built binaries but obfuscated or in some way pre-processed code that then requires an interpreter or VM to run on a system. You can still inspect and modify the code it's just much harder. A practically useful piece is missing but if it were under say a CC0 license you are still free to examine the image, attempt to reverse engineer any layers in it and to use, modify and distribute it as you see fit. It's a part of the commons just a less usefully mutable one than were it fully open sourece.
Somewhat similarly A bitmap and a photoshop file but no photoshop license is a bit like having the source, a binary and no compiler / build system. You are missing a crucial part for modification and re-use but you may not be free to say reverse engineer the Photoshop file if Adobe's "IP" protections extend to cover this format, or you can't/won't use photoshop.

My own contributions of bitmap images to this project have included the 'sources' the `.kra` files which include the layers of the images and allow their editing in the FLOSS drawing tool krita (For vectors I would use Inkscape and `.svg` files.):
https://github.com/the-turing-way/the-turing-way/pull/3058 . I appreciate that the scriberia images are generated by outside professionals who have their own established workflows based on proprietary tooling so it is impractical to atain this for all of the images in the project and I would argue that their utility is diminished because of this. Consider this PR where I modified a scriberia image https://github.com/the-turing-way/the-turing-way/pull/3049 and contributed the modified version back to the project, this would have been easier for me to do if I had access to the source files (and photoshop) but it was not impossible.

## Let us analogise to baking:

- If I give you the recipe for a cake the cake is source available
- If I give you the recipe and permission to share the recipe and modified versions of the recipe the cake is permissively licenced open source.
- If I specify a recessively heritable clause to the cake recipe license that specifies anyone who bakes these cakes and shares them with others must also include the recipe when they do so that recipe is weak copy left
- If I specify a dominantly heritable clause to the cake recipe that specifies anyone who bakes this cake a modification, say a new type of icing, that this modification too must be distributed under equivalent terms to the rest of the cake recipe, this recipe is strong copy left. 
- If I give you a cake and prohibit you from analysing that cake to infer it's ingredients and recipe that cake is patented and/or DRM protected.
- If I add a clause saying you can give away the cake you make with my recipe but you can sell them that recipe is a non-commercial license, if this is also copy left and you contribute your changes back then I can sell the cake either as if now contains your contributions under the same non-commercial terms.
- If I give you an open cake recipe and make you sign a contributor license agreement to the recipe that says any modifications you make to the cake and share also belong to me then I can take the improvements that you make to the cake combine them with my own and sell the result under a different proprietary license.
- If I bake cakes for everyone and no one reciprocates I'll run out of time and resources and then no one will have cake :(

This works just as well for instructions to make other physical things

Open source development, maintainership, and community management is a commons and should be governed like one.

**Comment by JimMadge** [comment]
Usually, I find loose use of "open source" from the software world irritating. I've seen things like publications, tutorials, policies being "open source" when there was no source and/or there was no free aspect (redistribution, modification, _etc._).

I wouldn't object to changing the language to say something less specific like "open and collaborative", making sure we keep text promoting our use of and support for FOSS.

I might need some convincing that this isn't just a semantic argument though.
I'm reminded of,

- Nitpicking about people saying Linux when they may mean GNU/Linux, some particular Linux distro, a broader set of software/technology related to Linux operating systems
- When talking about images having no source, the Linux kernel includes binary blobs (or at lest distributes them for you to use in builds), many projects will include objects with no easily-editable source (Nextcloud has example photographs and documents to populate new users files, for example)

I really like the quadrants on that norms against OSI approved figure by the way. Looking at that, I think I care much more about the norms and community ownership rather than whether something is technically OSI approved or not.

**Comment by AbcSxyZ** [comment]
## Is open source open source ?

> I would strongly favour using other terms to refer to adjacent concepts which diverge from this definition to avoid further terminological confusion.

There is definitively an incompatibility between The Turing Way's current use of the notion of open source and the traditional meaning given to the concept, represented by the Open Source Definition which refer only to software with some specific criteria. A situation that is truly a source of terminological confusion.

The thing is that we can see multiple types of digital resources that are composed of both a final usable element and a set of raw materials necessary for their production, materials which may be called sources in various case. The question seems to me to be whether talking about sources of digital resources is appropriate, and whether making these sources available can be described as « open source », like it can be here for The Turing Way, for a "book".

We could either be dealing with adjacent concepts where words are still lacking, and which could therefore be described in a different way, or we may not be dealing with an adjacent concept and the question then arises whether the Open Source Definition could be an appropriate definition of open source.

Is the conventional meaning given to the term appropriate?

## History of the Open Source Definition

> all largely converge on a definition that pretty much amounts to abiding by the FSF's four freedoms

The Open Source Definition is a direct legacy of the Free Software Definition as it is based on the [Debian Free Software Guideline](https://wiki.debian.org/DebianFreeSoftwareGuidelines), used almost identically apart from the rebranding. Everything is then compatible with the 4 freedoms of the [Free Software Definition](https://www.gnu.org/philosophy/free-sw.en.html#fs-definition).

To try to summarize this definition process which forms the foundations of the meaning of open source, "first" we have Eric Raymond who published [the Cathedral and the Bazaar](https://en.wikipedia.org/wiki/The_Cathedral_and_the_Bazaar) in 1997 to propose a development methodology inspired by Linux on what was still called free software, an essay that attracted a major player, Netscape, and inspired their strategy. An interest from the business world in so-called free software and a desire to reach them by some free software players like Eric Raymond, with in the background a latent problem of confusion surrounding the term free. In February 1998 during the period where Raymond was advising Netscape, a meeting was held with other free software actors, including [Christine Peterson](https://opensource.com/article/18/2/coining-term-open-source-software) who had a particular attention to these confusion factors, where the term was introduced (first informally) and the terminology problem discussed explicitly at some point in the meeting.

Open source was born (somehow), but still without any existing definition.

In parallel, the Debian project had issue with software policy because of their use of some "free software" which do not comply strictly with "copyleft" approach of the Free Software Foundation/Stallman, as a result [Bruce Perens suggested the Debian Free Software Guidelines](https://www.oreilly.com/openbook/opensources/book/perens.html) in 1997. Then these two stories merge: « Raymond insisted that Netscape's license comply with Debian's guidelines for it to be taken seriously as free software », « Raymond felt that the Debian Free Software Guidelines were the right document to define Open Source » (cf Perens), « [Bruce Perens] also suggested that the Debian Free Software Guidelines become the `Open Source Definition' » (cf [Raymond](http://catb.org/~esr/faqs/hacker-revenge.html)).

This is how the licensing guidelines of a project become the definition, the backbone of a new concept. Is it possible that this definition process produce a result with some limitations ? Or could it be a timeproof definition from a document that wasn't even thought for that at a time when the word was not even used 💪

The world may be more shaped by randomness than by visionaries.

## A license based definition: destined to be obsolete ?

Almost the entire Open Source Definition is about licensing criteria, but licences are not a required element for openness practices.

Our current need for licences depends on the legal copyright framework, being useful at first to build trust. Not used in the early days of computing when « open source » existed by default, that we can legitimately hope will no longer be necessary tomorrow (in the unlikely scenario that tomorrow exists).

Copyright is a whole philosophy about our relationship to what we call « intellectual property ». A philosophy about ownership reflected in the law that gives us by default (!) exclusive rights over our intellectual creations, prohibiting others from using them freely without an appropriate contract.

A copyright framework that does not provide a basic way to share widely our "property", a complex system such as with licenses from private organisations is then needed to be legally achieved. A philosophy inherited from the printing press era and whose latest developments date from around 1976, prior to the democratisation of digital technology.

For « literary work », there is societal and philosophical tension between a desire to possess and a desire to share, amplified by our new technological reality. Dating back to the 50s, as the software was initially sold bundled with the hardware with no direct commercial activity on it, the code circulated freely.

As it was still a new artefact, the software was not even protected by law, with important legal uncertainty until the 1976 US [Copyright Act](https://en.wikipedia.org/wiki/Copyright_Act_of_1976).

A notable illustration of this philosophical tension was in 1976 when Bill Gates sent « [An Open Letter to Hobbyists](https://en.wikipedia.org/wiki/An_Open_Letter_to_Hobbyists) » to the Homebrew Computer Club accusing them of being thieves by sharing with each other Micro-soft's first software product, a BASIC interpreter. In reaction to the letter, [Li-Chen Wang](https://en.wikipedia.org/wiki/Li-Chen_Wang), a member of the club, will release an alternative BASIC interpreter to be shared with a notice mentioning « copyleft, all wrongs reserved ».

A copyleft philosophy was taking shape that stands in opposition to copyright, one with the intention of sharing and the other of possessing.

In 80's, Richard Stallman gave some legal substance to this idea of copyleft through the free software movement and the creation of the GNU General Public Licenses, and then we started using licences partly out of necessity because of copyright laws, without other ways to guarantee sharing than using copyright against itself. The notion of copyleft was inspired for him by [a letter he received](https://www.gnu.org/graphics/copyleft-sticker.html) from Don Hopkins which used it.

There is an increasing tension between the legal framework and the reality of people practices with digital technologies, the practice of sharing becoming increasingly common in more and more areas even beyond software, the Creative Commons organisation being created in 2001 on this basis.

Over the years, a growing pressure is being put on the copyright framework to meet this need for sharing. There are emerging debates among legal experts with consideration for the integration of these sharing rights into copyright laws. Adrienne K. Goss in « [Codifying a Commons: Copyright, Copyleft, and the Creative Commons Project](https://scholarship.kentlaw.iit.edu/cklawreview/vol82/iss2/24/) » (2007) suggested for example to recognize associate rights with alternative circle than ©, with letter like NC [non-commercial] or PD [public Domain].

If one day the copyright framework is designed to provide a basic means of sharing adapted to digital technology (and openness practices), prioritising collective knowledge over commercial interests of a few, our current use of licences is destined to evolve and become outdated.

If the licensing system becomes outdated, then the whole Open Source Definition will inevitably become outdated, with open source that can no longer be defined simply in relation to licences.

Even if I'm not sure tomorrow exists, I can guarantee that tomorrow won't be like today, we're still in the early days of the digital revolution at the heart of even deeper societal changes.

## Source(s) and open source beyond software: some point of views

> I also suggest that the common core of these definitions is the one generally being alluded to by people who are at least somewhat informed about this issue.

With all the subtleties that make up the notion of open source, it seems that people are finding it hard to agree on a common meaning.

As I've some interest in the subject and I'm a bit confused myself about what this common definition could really be about, I'm collecting some opinions from people I see on the Internet who are writing about this notion: <https://open-source-undefined.org/resources/open-source-reflections.html>

To look at the use of the term for other types of resources, to consider the case of The Turing Way, a number of people tend to agree that the usage seems appropriate beyond software. I mentioned previously [two guys from GitHub](https://ben.balter.com/2014/01/27/open-collaboration/) who talked near 2014 notably about the text files of a blog, reflected in the GitHub's glossary. They were discussing with Karl Fogel who wrote a book called [Producing Open Source Software](https://producingoss.com/) in 2005.

> **Ben Balter:** Can we call this blog post open source?  
> **Karl Fogel:** Well, I think that's an easy one: yes, it's open source.  
> *Src:* [benbalter/benbalter.github.com/pull/98](https://github.com/benbalter/benbalter.github.com/pull/98)

I sent the image of the first comment that asks whether it is an open source image to members of the Open Source Initiative, one of them replying that he « would say it's an open source image. ». Russ Nelson, one of the co-founding members and President in February 2005 of the Open Source Initiative, participated in an editorial on the theme « Defining Open Source » from the TIM Review in 2007 where [he states](https://timreview.ca/issue/2007/september) that « the concept is applicable to anything which has separable design elements ».

I regularly ask people who work in open source whether they know what open source means, whether making the sources of digital resources available is open source. I've never met anyone who has told me that wasn't the case, nobody giving a reasoned explanation that the concept would only be appropriate for software. @malvikasharan & @JimMadge's comments here are somewhat in line with this trend.

It's also interesting to see whether people outside the software world can use the term source or even open source. Being myself in some ways more oriented towards open education, on this side there is the article I mentioned that suggests the notion of « [open source educational resource](https://arxiv.org/abs/2107.14330) ». We can find out the Journal of Open Source Education that puts an emphasis on availability of "[source files](https://jose.theoj.org/about)" in their about section. In a (French-speaking) [OER factory](https://fabriquerel.org/rel-disponibles/), it is often possible to download a "source file" [fichier source]. And of course, as it is the root of this discussion, the term open source is also used by The Turing Way.

In his move to liberate literary works and also to help the commercial and non-commercial sectors with Creative Commons, Lessig's approach has been criticised as lacking clarity on the meaning of freedom by [free software players](https://mako.cc/writing/toward_a_standard_of_freedom.html) (including [Stallman](https://www.fsf.org/blogs/rms/entry-20050920.html)). In their attempt to clarify the meaning of freedom where it was argued that it was essential to follow the meaning given by the Free Software Definition, these people being more aware of what freedom is, the [definition of Free Cultural Works](https://freedomdefined.org/Definition) was launched which specify the availability of "source data".

It appears that there is a real question as to whether making the sources of digital resources available can be described as open source, to know whether open source resources are indeed a subject.

Is it possible that the Open Source Definition might not be an appropriate definition of open source because it doesn't consider the right types of resources, and that if it's already not considering the right type of resources, it might also be wrong on the way to do it?

Do you think that open source is open source ? What is open source ?

**Comment by AbcSxyZ** [comment]
Closed by #3889
